### ISSUE TITLE
Consider creating a base command

### ISSUE THREAD

**Issue by dcowden** [entech281/Robot2020#20]
Our commands do not all extend from a base command in our packages.  That means we don't have a place to put common code. 

consider this:
https://github.com/entech281/Macarena2018/blob/master/src/main/java/frc/team281/robot/commands/BaseCommand.java

it has two things of interest:
(1) it forces setting a timeout. our current commands do not set a timeout-- what is the effective timeout then? there's an answer, but you have to dig through the wpilib to find it

(2) we dont have a logger, so debugging is hard.  the above class makes a datalogger so that every command has one available

**Comment by Plaba** [comment]
Fixed
